[package]
name = "glissade"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Quentin Bramas", "Augustin Albert"]
license = "MIT"
description = "Create animated presentations in Typst and export them to the web."
repository = "https://github.com/Bramas/glissade"
keywords = ["animation", "video", "slide", "slides", "lecture", "manim", "beamer", "ffmpeg", "talk"]
categories = ["presentation", "scripting", "fun"]
exclude = [ "docs", "examples"]
