// Placeholder for the Glissade playground bundle.
//
// The deployed site generates site/glissade.generated.typ from the source
// modules with:
//
//   npm run build:playground-lib
//
// Do not edit this file by hand. The generated file is intentionally ignored
// by git so the playground bundle cannot accidentally replace this placeholder.
