// Placeholder for the Glissade playground bundle.
//
// The deployed site generates this file from the source modules with:
//
//   node bin/build-playground-library.mjs
//
// Do not edit this file by hand. The generated file is intentionally built in
// CI/CD so the playground uses the current library implementation.
